import { create } from 'zustand'
import { createJSONStorage, persist } from 'zustand/middleware'
import { shallow } from 'zustand/shallow'

const merchantSignupStore = create(
  persist(
    (set) => ({
      activeStep: 1,
      last_name: '',
      first_name: '',
      email: '',
      phone: '',
      password: '',
      id_number: '',
      id_type: '',
      id_front_image_url: '',
      id_back_image_url: '',
      business_name: '',
      registration_number: '',
      business_type: '',
      address: '',
      city: '',
      state: '',
      country: '',
      postal_code: '',
      wallet_address: '',
      wallet_address_type: '',
      wallet_address_nickname: '',
      setLastName: (last_name) => set(() => ({ last_name })),
      setFirstName: (first_name) => set(() => ({ first_name })),
      setEmail: (email) => set(() => ({ email })),
      setPhone: (phone) => set(() => ({ phone })),
      setPassword: (password) => set(() => ({ password })),
      setIdNumber: (id_number) => set(() => ({ id_number })),
      setIdType: (id_type) => set(() => ({ id_type })),
      setIdFrontImageUrl: (id_front_image_url) => set(() => ({ id_front_image_url })),
      setIdBackImageUrl: (id_back_image_url) => set(() => ({ id_back_image_url })),
      setBusinessName: (business_name) => set(() => ({ business_name })),
      setRegistrationNumber: (registration_number) => set(() => ({ registration_number })),
      setBusinessType: (business_type) => set(() => ({ business_type })),
      setAddress: (address) => set(() => ({ address })),
      setCity: (city) => set(() => ({ city })),
      setState: (state) => set(() => ({ state })),
      setCountry: (country) => set(() => ({ country })),
      setPostalCode: (postal_code) => set(() => ({ postal_code })),
      setWalletAddress: (wallet_address) => set(() => ({ wallet_address })),
      setWalletAddressType: (wallet_address_type) => set(() => ({ wallet_address_type })),
      setWalletAddressNickname: (wallet_address_nickname) => set(() => ({ wallet_address_nickname })),
      setActiveStep: (step) => set(() => ({ activeStep: step })),
    }),
    {
      name: 'useMerchantSignupStore',
      storage: createJSONStorage(() => sessionStorage),
    },
  ),
)

export const useMerchantSignupStore = () => {
  const store = merchantSignupStore(
    ({
      activeStep,
      last_name,
      first_name,
      email,
      phone,
      password,
      id_number,
      id_type,
      id_front_image_url,
      id_back_image_url,
      business_name,
      registration_number,
      business_type,
      address,
      city,
      state,
      country,
      postal_code,
      wallet_address,
      wallet_address_type,
      wallet_address_nickname,
      setLastName,
      setFirstName,
      setEmail,
      setPhone,
      setPassword,
      setIdNumber,
      setIdType,
      setIdFrontImageUrl,
      setIdBackImageUrl,
      setBusinessName,
      setRegistrationNumber,
      setBusinessType,
      setAddress,
      setCity,
      setState,
      setCountry,
      setPostalCode,
      setWalletAddress,
      setWalletAddressType,
      setWalletAddressNickname,
      setActiveStep
    }) => ({
      activeStep,
      last_name,
      first_name,
      email,
      phone,
      password,
      id_number,
      id_type,
      id_front_image_url,
      id_back_image_url,
      business_name,
      registration_number,
      business_type,
      address,
      city,
      state,
      country,
      postal_code,
      wallet_address,
      wallet_address_type,
      wallet_address_nickname,
      setLastName,
      setFirstName,
      setEmail,
      setPhone,
      setPassword,
      setIdNumber,
      setIdType,
      setIdFrontImageUrl,
      setIdBackImageUrl,
      setBusinessName,
      setRegistrationNumber,
      setBusinessType,
      setAddress,
      setCity,
      setState,
      setCountry,
      setPostalCode,
      setWalletAddress,
      setWalletAddressType,
      setWalletAddressNickname,
      setActiveStep
    }),
    shallow,
  )

  return store
}
