export default Object.freeze({
  ADMIN_SIGN_IN_PAGE: '/admin/signin',
  ADMIN_VERIFY_SELF_PAGE: '/admin/verify-self/:code',
  ADMIN_VIEW_ADMINS_PAGE: 'users/admins',
  ADMIN_VIEW_BUYERS_PAGE: 'users/buyers',
  ADMIN_VIEW_INSIGHT_ORDERS_PAGE: 'insight/orders',
  ADMIN_VIEW_INSIGHT_PRODUCTS_PAGE: 'insight/products',
  ADMIN_VIEW_MERCHANTS_PAGE: 'users/merchants',
  BUYER_SIGN_IN_PAGE: '/signin',
  BUYER_SIGN_UP_PAGE: '/signup',
  CART_DASHBOARD_PAGE: 'cart',
  PASSWORD_RESET_PAGE: '/password-reset/:token',
  DASHBOARD_PAGE: 'dashboard',
  FORGOT_PASSWORD_PAGE: '/forgot-password',
  HOME_PAGE: '/',
  MERCHANT_PRODUCT_CREATE_PAGE: 'products/create',
  MERCHANT_PRODUCT_PAGE: 'products',
  MERCHANT_SIGN_IN_PAGE: '/merchant/signin',
  MERCHANT_SIGN_UP_PAGE: '/merchant/signup',
  NOTIFICATION_PAGE: 'notifications',
  ORDERS_PAGE: 'orders',
  ORDER_INFO_PAGE: 'orders/:orderId',
  PROFILE_PAGE: 'profile',
  TERMS_AND_CONDITION_PAGE: '/terms-and-condition',
  TRACK_ORDER_PAGE: 'track-orders',
  WALLET_PAGE: 'wallet'
})
